workflows:
  android-workflow:
    name: Android Workflow
    working_directory: mobile_app
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      android_signing:
        - keystore_reference
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "io.codemagic.flutteryaml"
        GOOGLE_PLAY_TRACK: "alpha"
      flutter: stable
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Flutter unit tests
        script: |
          flutter test
        ignore_failure: true
      - name: Build AAB with Flutter
        script: |
          BUILD_NUMBER=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME" --tracks="$GOOGLE_PLAY_TRACK") + 1))      
          flutter build appbundle --release \
            --build-name=1.0.$BUILD_NUMBER \
            --build-number=$BUILD_NUMBER
    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log

  ios-workflow:
    name: Build iOS IPA
    working_directory: mobile_app
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install CocoaPods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Build unsigned iOS IPA
        script: |
          flutter build ipa --no-codesign --verbose
      - name: Package IPA
        script: |
          cd build/ios/archive/Runner.xcarchive/Products/Applications
          mv Runner.app Payload.app       # or rename to your app’s name
          mkdir Payload
          mv Payload.app Payload/
          zip -r Payload.ipa Payload/
          mv Payload.ipa "$CM_BUILD_DIR"
    artifacts:
      - Payload.ipa
