name: Build iOS IPA

on:
  push:
    branches:
      - main

jobs:
  build_ipa:
    runs-on: macos-latest

    defaults:
      run:
        working-directory: mobile_app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8'

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Build unsigned iOS IPA
        run: flutter build ipa --simulator --no-codesign

      - name: Compress Archives and IPAs
        run: |
          cd build/ios/archive/Runner.xcarchive/Products/Applications
          mv Runner.app Pokedex.app
          mkdir Payload
          mv Pokedex.app Payload/
          zip -r Payload.ipa Payload/

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: Payload.ipa
          path: mobile_app/build/ios/archive/Runner.xcarchive/Products/Applications/Payload.ipa

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: Podfile
          path: mobile_app/ios/Podfile